directories:
  output: release
  buildResources: build
appId: com.shadowhawk.minecraft-server-manager
productName: ShadowHawk Minecraft Server Manager
files:
  - filter:
      - app/**/*
      - renderer/**/*
      - node_modules/**/*
mac:
  category: public.app-category.games
win:
  target: nsis
linux:
  target: AppImage
electronVersion: 26.6.10
